name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6
            - name: Welcome message
              run: echo "Hello, World! my GH Actionsworkflow"

            - name: List files
              run: ls

            - name: Read File
              run: cat README.md